# This is a basic workflow to help you get started with Actions

name: linux

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on:  ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v6

      - name: setup prerequisites (linux)
        shell: bash
        run: sudo apt install pkg-config libudev-dev libusb-1.0-0-dev

      - name: fetch hidapi
        uses: actions/checkout@v6
        with:
          repository: libusb/hidapi
          path: hidapi

      - name: compile hidapitester Makefile
        shell: bash
        run: HIDAPI_DIR=./hidapi make

      - name: run hidapitester (Makefile)
        shell: bash
        run: |
          ./hidapitester --version && output=$(./hidapitester --list 2>&1) || [[ "$output" == *"No HID devices found"* ]]

      - name: Configure hidapitester with CMake
        run: |
          mkdir build
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build hidapitester with CMake
        run: cmake --build build --config Release

      - name: Run hidapitester (CMake)
        run: |
          ./build/hidapitester --version && output=$(./build/hidapitester --list 2>&1) || [[ "$output" == *"No HID devices found"* ]]
        # (we need the grep guard because Linux runners no longer return any devices)

      - name: Upload hidapitester artifacts (PR)
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v7
        with:
          name: hidapitester-linux
          path: |
            build/hidapitester
          retention-days: 2

      - name: Upload hidapitester artifacts (main)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v7
        with:
          name: hidapitester-linux
          path: |
            build/hidapitester
